/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('continents').del()
  await knex('continents').insert([
    { code: 'AF', name: 'Africa'},
    { code: 'AN', name: 'Antarctica'},
    { code: 'AS', name: 'Asia'},
    { code: 'EU', name: 'Europe'},
    { code: 'NA', name: 'North America'},
    { code: 'OC', name: 'Oceania'},
    { code: 'SA', name: 'South America'},
  ]);

  await knex('countries').del()
  await knex('countries').insert([
    { code: 'AF', name: 'Afghanistan', phone: 93, symbol: '؋', capital: 'Kabul', currency: 'AFN', continent_code: 'AS', alpha_3: 'AFG'},
    { code: 'AX', name: 'Aland Islands', phone: 358, symbol: '€', capital: 'Mariehamn', currency: 'EUR', continent_code: 'EU', alpha_3: 'ALA'},
    { code: 'AL', name: 'Albania', phone: 355, symbol: 'Lek', capital: 'Tirana', currency: 'ALL', continent_code: 'EU', alpha_3: 'ALB'},
    { code: 'DZ', name: 'Algeria', phone: 213, symbol: 'دج', capital: 'Algiers', currency: 'DZD', continent_code: 'AF', alpha_3: 'DZA'},
    { code: 'AS', name: 'American Samoa', phone: 1684, symbol: '$', capital: 'Pago Pago', currency: 'USD', continent_code: 'OC', alpha_3: 'ASM'},
    { code: 'AD', name: 'Andorra', phone: 376, symbol: '€', capital: 'Andorra la Vella', currency: 'EUR', continent_code: 'EU', alpha_3: 'AND'},
    { code: 'AO', name: 'Angola', phone: 244, symbol: 'Kz', capital: 'Luanda', currency: 'AOA', continent_code: 'AF', alpha_3: 'AGO'},
    { code: 'AI', name: 'Anguilla', phone: 1264, symbol: '$', capital: 'The Valley', currency: 'XCD', continent_code: 'NA', alpha_3: 'AIA'},
    { code: 'AQ', name: 'Antarctica', phone: 672, symbol: '$', capital: 'Antarctica', currency: 'AAD', continent_code: 'AN', alpha_3: 'ATA'},
    { code: 'AG', name: 'Antigua and Barbuda', phone: 1268, symbol: '$', capital: 'St. Johns', currency: 'XCD', continent_code: 'NA', alpha_3: 'ATG'},
    { code: 'AR', name: 'Argentina', phone: 54, symbol: '$', capital: 'Buenos Aires', currency: 'ARS', continent_code: 'SA', alpha_3: 'ARG'},
    { code: 'AM', name: 'Armenia', phone: 374, symbol: '֏', capital: 'Yerevan', currency: 'AMD', continent_code: 'AS', alpha_3: 'ARM'},
    { code: 'AW', name: 'Aruba', phone: 297, symbol: 'ƒ', capital: 'Oranjestad', currency: 'AWG', continent_code: 'NA', alpha_3: 'ABW'},
    { code: 'AU', name: 'Australia', phone: 61, symbol: '$', capital: 'Canberra', currency: 'AUD', continent_code: 'OC', alpha_3: 'AUS'},
    { code: 'AT', name: 'Austria', phone: 43, symbol: '€', capital: 'Vienna', currency: 'EUR', continent_code: 'EU', alpha_3: 'AUT'},
    { code: 'AZ', name: 'Azerbaijan', phone: 994, symbol: 'm', capital: 'Baku', currency: 'AZN', continent_code: 'AS', alpha_3: 'AZE'},
    { code: 'BS', name: 'Bahamas', phone: 1242, symbol: 'B$', capital: 'Nassau', currency: 'BSD', continent_code: 'NA', alpha_3: 'BHS'},
    { code: 'BH', name: 'Bahrain', phone: 973, symbol: '.د.ب', capital: 'Manama', currency: 'BHD', continent_code: 'AS', alpha_3: 'BHR'},
    { code: 'BD', name: 'Bangladesh', phone: 880, symbol: '৳', capital: 'Dhaka', currency: 'BDT', continent_code: 'AS', alpha_3: 'BGD'},
    { code: 'BB', name: 'Barbados', phone: 1246, symbol: 'Bds$', capital: 'Bridgetown', currency: 'BBD', continent_code: 'NA', alpha_3: 'BRB'},
    { code: 'BY', name: 'Belarus', phone: 375, symbol: 'Br', capital: 'Minsk', currency: 'BYN', continent_code: 'EU', alpha_3: 'BLR'},
    { code: 'BE', name: 'Belgium', phone: 32, symbol: '€', capital: 'Brussels', currency: 'EUR', continent_code: 'EU', alpha_3: 'BEL'},
    { code: 'BZ', name: 'Belize', phone: 501, symbol: '$', capital: 'Belmopan', currency: 'BZD', continent_code: 'NA', alpha_3: 'BLZ'},
    { code: 'BJ', name: 'Benin', phone: 229, symbol: 'CFA', capital: 'Porto-Novo', currency: 'XOF', continent_code: 'AF', alpha_3: 'BEN'},
    { code: 'BM', name: 'Bermuda', phone: 1441, symbol: '$', capital: 'Hamilton', currency: 'BMD', continent_code: 'NA', alpha_3: 'BMU'},
    { code: 'BT', name: 'Bhutan', phone: 975, symbol: 'Nu.', capital: 'Thimphu', currency: 'BTN', continent_code: 'AS', alpha_3: 'BTN'},
    { code: 'BO', name: 'Bolivia', phone: 591, symbol: 'Bs.', capital: 'Sucre', currency: 'BOB', continent_code: 'SA', alpha_3: 'BOL'},
    { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', phone: 599, symbol: '$', capital: 'Kralendijk', currency: 'USD', continent_code: 'NA', alpha_3: 'BES'},
    { code: 'BA', name: 'Bosnia and Herzegovina', phone: 387, symbol: 'KM', capital: 'Sarajevo', currency: 'BAM', continent_code: 'EU', alpha_3: 'BIH'},
    { code: 'BW', name: 'Botswana', phone: 267, symbol: 'P', capital: 'Gaborone', currency: 'BWP', continent_code: 'AF', alpha_3: 'BWA'},
    { code: 'BV', name: 'Bouvet Island', phone: 55, symbol: 'kr', capital: '', currency: 'NOK', continent_code: 'AN', alpha_3: 'BVT'},
    { code: 'BR', name: 'Brazil', phone: 55, symbol: 'R$', capital: 'Brasilia', currency: 'BRL', continent_code: 'SA', alpha_3: 'BRA'},
    { code: 'IO', name: 'British Indian Ocean Territory', phone: 246, symbol: '$', capital: 'Diego Garcia', currency: 'USD', continent_code: 'AS', alpha_3: 'IOT'},
    { code: 'BN', name: 'Brunei Darussalam', phone: 673, symbol: 'B$', capital: 'Bandar Seri Begawan', currency: 'BND', continent_code: 'AS', alpha_3: 'BRN'},
    { code: 'BG', name: 'Bulgaria', phone: 359, symbol: 'Лв.', capital: 'Sofia', currency: 'BGN', continent_code: 'EU', alpha_3: 'BGR'},
    { code: 'BF', name: 'Burkina Faso', phone: 226, symbol: 'CFA', capital: 'Ouagadougou', currency: 'XOF', continent_code: 'AF', alpha_3: 'BFA'},
    { code: 'BI', name: 'Burundi', phone: 257, symbol: 'FBu', capital: 'Bujumbura', currency: 'BIF', continent_code: 'AF', alpha_3: 'BDI'},
    { code: 'KH', name: 'Cambodia', phone: 855, symbol: 'KHR', capital: 'Phnom Penh', currency: 'KHR', continent_code: 'AS', alpha_3: 'KHM'},
    { code: 'CM', name: 'Cameroon', phone: 237, symbol: 'FCFA', capital: 'Yaounde', currency: 'XAF', continent_code: 'AF', alpha_3: 'CMR'},
    { code: 'CA', name: 'Canada', phone: 1, symbol: '$', capital: 'Ottawa', currency: 'CAD', continent_code: 'NA', alpha_3: 'CAN'},
    { code: 'CV', name: 'Cape Verde', phone: 238, symbol: '$', capital: 'Praia', currency: 'CVE', continent_code: 'AF', alpha_3: 'CPV'},
    { code: 'KY', name: 'Cayman Islands', phone: 1345, symbol: '$', capital: 'George Town', currency: 'KYD', continent_code: 'NA', alpha_3: 'CYM'},
    { code: 'CF', name: 'Central African Republic', phone: 236, symbol: 'FCFA', capital: 'Bangui', currency: 'XAF', continent_code: 'AF', alpha_3: 'CAF'},
    { code: 'TD', name: 'Chad', phone: 235, symbol: 'FCFA', capital: 'NDjamena', currency: 'XAF', continent_code: 'AF', alpha_3: 'TCD'},
    { code: 'CL', name: 'Chile', phone: 56, symbol: '$', capital: 'Santiago', currency: 'CLP', continent_code: 'SA', alpha_3: 'CHL'},
    { code: 'CN', name: 'China', phone: 86, symbol: '¥', capital: 'Beijing', currency: 'CNY', continent_code: 'AS', alpha_3: 'CHN'},
    { code: 'CX', name: 'Christmas Island', phone: 61, symbol: '$', capital: 'Flying Fish Cove', currency: 'AUD', continent_code: 'AS', alpha_3: 'CXR'},
    { code: 'CC', name: 'Cocos (Keeling) Islands', phone: 672, symbol: '$', capital: 'West Island', currency: 'AUD', continent_code: 'AS', alpha_3: 'CCK'},
    { code: 'CO', name: 'Colombia', phone: 57, symbol: '$', capital: 'Bogota', currency: 'COP', continent_code: 'SA', alpha_3: 'COL'},
    { code: 'KM', name: 'Comoros', phone: 269, symbol: 'CF', capital: 'Moroni', currency: 'KMF', continent_code: 'AF', alpha_3: 'COM'},
    { code: 'CG', name: 'Congo', phone: 242, symbol: 'FC', capital: 'Brazzaville', currency: 'XAF', continent_code: 'AF', alpha_3: 'COG'},
    { code: 'CD', name: 'Congo, Democratic Republic of the Congo', phone: 242, symbol: 'FC', capital: 'Kinshasa', currency: 'CDF', continent_code: 'AF', alpha_3: 'COD'},
    { code: 'CK', name: 'Cook Islands', phone: 682, symbol: '$', capital: 'Avarua', currency: 'NZD', continent_code: 'OC', alpha_3: 'COK'},
    { code: 'CR', name: 'Costa Rica', phone: 506, symbol: '₡', capital: 'San Jose', currency: 'CRC', continent_code: 'NA', alpha_3: 'CRI'},
    { code: 'CI', name: 'Cote DIvoire', phone: 225, symbol: 'CFA', capital: 'Yamoussoukro', currency: 'XOF', continent_code: 'AF', alpha_3: 'CIV'},
    { code: 'HR', name: 'Croatia', phone: 385, symbol: 'kn', capital: 'Zagreb', currency: 'HRK', continent_code: 'EU', alpha_3: 'HRV'},
    { code: 'CU', name: 'Cuba', phone: 53, symbol: '$', capital: 'Havana', currency: 'CUP', continent_code: 'NA', alpha_3: 'CUB'},
    { code: 'CW', name: 'Curacao', phone: 599, symbol: 'ƒ', capital: 'Willemstad', currency: 'ANG', continent_code: 'NA', alpha_3: 'CUW'},
    { code: 'CY', name: 'Cyprus', phone: 357, symbol: '€', capital: 'Nicosia', currency: 'EUR', continent_code: 'AS', alpha_3: 'CYP'},
    { code: 'CZ', name: 'Czech Republic', phone: 420, symbol: 'Kč', capital: 'Prague', currency: 'CZK', continent_code: 'EU', alpha_3: 'CZE'},
    { code: 'DK', name: 'Denmark', phone: 45, symbol: 'Kr.', capital: 'Copenhagen', currency: 'DKK', continent_code: 'EU', alpha_3: 'DNK'},
    { code: 'DJ', name: 'Djibouti', phone: 253, symbol: 'Fdj', capital: 'Djibouti', currency: 'DJF', continent_code: 'AF', alpha_3: 'DJI'},
    { code: 'DM', name: 'Dominica', phone: 1767, symbol: '$', capital: 'Roseau', currency: 'XCD', continent_code: 'NA', alpha_3: 'DMA'},
    { code: 'DO', name: 'Dominican Republic', phone: 1809, symbol: '$', capital: 'Santo Domingo', currency: 'DOP', continent_code: 'NA', alpha_3: 'DOM'},
    { code: 'EC', name: 'Ecuador', phone: 593, symbol: '$', capital: 'Quito', currency: 'USD', continent_code: 'SA', alpha_3: 'ECU'},
    { code: 'EG', name: 'Egypt', phone: 20, symbol: 'ج.م', capital: 'Cairo', currency: 'EGP', continent_code: 'AF', alpha_3: 'EGY'},
    { code: 'SV', name: 'El Salvador', phone: 503, symbol: '$', capital: 'San Salvador', currency: 'USD', continent_code: 'NA', alpha_3: 'SLV'},
    { code: 'GQ', name: 'Equatorial Guinea', phone: 240, symbol: 'FCFA', capital: 'Malabo', currency: 'XAF', continent_code: 'AF', alpha_3: 'GNQ'},
    { code: 'ER', name: 'Eritrea', phone: 291, symbol: 'Nfk', capital: 'Asmara', currency: 'ERN', continent_code: 'AF', alpha_3: 'ERI'},
    { code: 'EE', name: 'Estonia', phone: 372, symbol: '€', capital: 'Tallinn', currency: 'EUR', continent_code: 'EU', alpha_3: 'EST'},
    { code: 'ET', name: 'Ethiopia', phone: 251, symbol: 'Nkf', capital: 'Addis Ababa', currency: 'ETB', continent_code: 'AF', alpha_3: 'ETH'},
    { code: 'FK', name: 'Falkland Islands (Malvinas)', phone: 500, symbol: '£', capital: 'Stanley', currency: 'FKP', continent_code: 'SA', alpha_3: 'FLK'},
    { code: 'FO', name: 'Faroe Islands', phone: 298, symbol: 'Kr.', capital: 'Torshavn', currency: 'DKK', continent_code: 'EU', alpha_3: 'FRO'},
    { code: 'FJ', name: 'Fiji', phone: 679, symbol: 'FJ$', capital: 'Suva', currency: 'FJD', continent_code: 'OC', alpha_3: 'FJI'},
    { code: 'FI', name: 'Finland', phone: 358, symbol: '€', capital: 'Helsinki', currency: 'EUR', continent_code: 'EU', alpha_3: 'FIN'},
    { code: 'FR', name: 'France', phone: 33, symbol: '€', capital: 'Paris', currency: 'EUR', continent_code: 'EU', alpha_3: 'FRA'},
    { code: 'GF', name: 'French Guiana', phone: 594, symbol: '€', capital: 'Cayenne', currency: 'EUR', continent_code: 'SA', alpha_3: 'GUF'},
    { code: 'PF', name: 'French Polynesia', phone: 689, symbol: '₣', capital: 'Papeete', currency: 'XPF', continent_code: 'OC', alpha_3: 'PYF'},
    { code: 'TF', name: 'French Southern Territories', phone: 262, symbol: '€', capital: 'Port-aux-Francais', currency: 'EUR', continent_code: 'AN', alpha_3: 'ATF'},
    { code: 'GA', name: 'Gabon', phone: 241, symbol: 'FCFA', capital: 'Libreville', currency: 'XAF', continent_code: 'AF', alpha_3: 'GAB'},
    { code: 'GM', name: 'Gambia', phone: 220, symbol: 'D', capital: 'Banjul', currency: 'GMD', continent_code: 'AF', alpha_3: 'GMB'},
    { code: 'GE', name: 'Georgia', phone: 995, symbol: 'ლ', capital: 'Tbilisi', currency: 'GEL', continent_code: 'AS', alpha_3: 'GEO'},
    { code: 'DE', name: 'Germany', phone: 49, symbol: '€', capital: 'Berlin', currency: 'EUR', continent_code: 'EU', alpha_3: 'DEU'},
    { code: 'GH', name: 'Ghana', phone: 233, symbol: 'GH₵', capital: 'Accra', currency: 'GHS', continent_code: 'AF', alpha_3: 'GHA'},
    { code: 'GI', name: 'Gibraltar', phone: 350, symbol: '£', capital: 'Gibraltar', currency: 'GIP', continent_code: 'EU', alpha_3: 'GIB'},
    { code: 'GR', name: 'Greece', phone: 30, symbol: '€', capital: 'Athens', currency: 'EUR', continent_code: 'EU', alpha_3: 'GRC'},
    { code: 'GL', name: 'Greenland', phone: 299, symbol: 'Kr.', capital: 'Nuuk', currency: 'DKK', continent_code: 'NA', alpha_3: 'GRL'},
    { code: 'GD', name: 'Grenada', phone: 1473, symbol: '$', capital: 'St. Georges', currency: 'XCD', continent_code: 'NA', alpha_3: 'GRD'},
    { code: 'GP', name: 'Guadeloupe', phone: 590, symbol: '€', capital: 'Basse-Terre', currency: 'EUR', continent_code: 'NA', alpha_3: 'GLP'},
    { code: 'GU', name: 'Guam', phone: 1671, symbol: '$', capital: 'Hagatna', currency: 'USD', continent_code: 'OC', alpha_3: 'GUM'},
    { code: 'GT', name: 'Guatemala', phone: 502, symbol: 'Q', capital: 'Guatemala City', currency: 'GTQ', continent_code: 'NA', alpha_3: 'GTM'},
    { code: 'GG', name: 'Guernsey', phone: 44, symbol: '£', capital: 'St Peter Port', currency: 'GBP', continent_code: 'EU', alpha_3: 'GGY'},
    { code: 'GN', name: 'Guinea', phone: 224, symbol: 'FG', capital: 'Conakry', currency: 'GNF', continent_code: 'AF', alpha_3: 'GIN'},
    { code: 'GW', name: 'Guinea-Bissau', phone: 245, symbol: 'CFA', capital: 'Bissau', currency: 'XOF', continent_code: 'AF', alpha_3: 'GNB'},
    { code: 'GY', name: 'Guyana', phone: 592, symbol: '$', capital: 'Georgetown', currency: 'GYD', continent_code: 'SA', alpha_3: 'GUY'},
    { code: 'HT', name: 'Haiti', phone: 509, symbol: 'G', capital: 'Port-au-Prince', currency: 'HTG', continent_code: 'NA', alpha_3: 'HTI'},
    { code: 'HM', name: 'Heard Island and Mcdonald Islands', phone: 0, symbol: '$', capital: '', currency: 'AUD', continent_code: 'AN', alpha_3: 'HMD'},
    { code: 'VA', name: 'Holy See (Vatican City State)', phone: 39, symbol: '€', capital: 'Vatican City', currency: 'EUR', continent_code: 'EU', alpha_3: 'VAT'},
    { code: 'HN', name: 'Honduras', phone: 504, symbol: 'L', capital: 'Tegucigalpa', currency: 'HNL', continent_code: 'NA', alpha_3: 'HND'},
    { code: 'HK', name: 'Hong Kong', phone: 852, symbol: '$', capital: 'Hong Kong', currency: 'HKD', continent_code: 'AS', alpha_3: 'HKG'},
    { code: 'HU', name: 'Hungary', phone: 36, symbol: 'Ft', capital: 'Budapest', currency: 'HUF', continent_code: 'EU', alpha_3: 'HUN'},
    { code: 'IS', name: 'Iceland', phone: 354, symbol: 'kr', capital: 'Reykjavik', currency: 'ISK', continent_code: 'EU', alpha_3: 'ISL'},
    { code: 'IN', name: 'India', phone: 91, symbol: '₹', capital: 'New Delhi', currency: 'INR', continent_code: 'AS', alpha_3: 'IND'},
    { code: 'ID', name: 'Indonesia', phone: 62, symbol: 'Rp', capital: 'Jakarta', currency: 'IDR', continent_code: 'AS', alpha_3: 'IDN'},
    { code: 'IR', name: 'Iran, Islamic Republic of', phone: 98, symbol: '﷼', capital: 'Tehran', currency: 'IRR', continent_code: 'AS', alpha_3: 'IRN'},
    { code: 'IQ', name: 'Iraq', phone: 964, symbol: 'د.ع', capital: 'Baghdad', currency: 'IQD', continent_code: 'AS', alpha_3: 'IRQ'},
    { code: 'IE', name: 'Ireland', phone: 353, symbol: '€', capital: 'Dublin', currency: 'EUR', continent_code: 'EU', alpha_3: 'IRL'},
    { code: 'IM', name: 'Isle of Man', phone: 44, symbol: '£', capital: 'Douglas, Isle of Man', currency: 'GBP', continent_code: 'EU', alpha_3: 'IMN'},
    { code: 'IL', name: 'Israel', phone: 972, symbol: '₪', capital: 'Jerusalem', currency: 'ILS', continent_code: 'AS', alpha_3: 'ISR'},
    { code: 'IT', name: 'Italy', phone: 39, symbol: '€', capital: 'Rome', currency: 'EUR', continent_code: 'EU', alpha_3: 'ITA'},
    { code: 'JM', name: 'Jamaica', phone: 1876, symbol: 'J$', capital: 'Kingston', currency: 'JMD', continent_code: 'NA', alpha_3: 'JAM'},
    { code: 'JP', name: 'Japan', phone: 81, symbol: '¥', capital: 'Tokyo', currency: 'JPY', continent_code: 'AS', alpha_3: 'JPN'},
    { code: 'JE', name: 'Jersey', phone: 44, symbol: '£', capital: 'Saint Helier', currency: 'GBP', continent_code: 'EU', alpha_3: 'JEY'},
    { code: 'JO', name: 'Jordan', phone: 962, symbol: 'ا.د', capital: 'Amman', currency: 'JOD', continent_code: 'AS', alpha_3: 'JOR'},
    { code: 'KZ', name: 'Kazakhstan', phone: 7, symbol: 'лв', capital: 'Astana', currency: 'KZT', continent_code: 'AS', alpha_3: 'KAZ'},
    { code: 'KE', name: 'Kenya', phone: 254, symbol: 'KSh', capital: 'Nairobi', currency: 'KES', continent_code: 'AF', alpha_3: 'KEN'},
    { code: 'KI', name: 'Kiribati', phone: 686, symbol: '$', capital: 'Tarawa', currency: 'AUD', continent_code: 'OC', alpha_3: 'KIR'},
    { code: 'KP', name: 'Korea, Democratic Peoples Republic of', phone: 850, symbol: '₩', capital: 'Pyongyang', currency: 'KPW', continent_code: 'AS', alpha_3: 'PRK'},
    { code: 'KR', name: 'Korea, Republic of', phone: 82, symbol: '₩', capital: 'Seoul', currency: 'KRW', continent_code: 'AS', alpha_3: 'KOR'},
    { code: 'XK', name: 'Kosovo', phone: 383, symbol: '€', capital: 'Pristina', currency: 'EUR', continent_code: 'EU', alpha_3: 'XKX'},
    { code: 'KW', name: 'Kuwait', phone: 965, symbol: 'ك.د', capital: 'Kuwait City', currency: 'KWD', continent_code: 'AS', alpha_3: 'KWT'},
    { code: 'KG', name: 'Kyrgyzstan', phone: 996, symbol: 'лв', capital: 'Bishkek', currency: 'KGS', continent_code: 'AS', alpha_3: 'KGZ'},
    { code: 'LA', name: 'Lao Peoples Democratic Republic', phone: 856, symbol: '₭', capital: 'Vientiane', currency: 'LAK', continent_code: 'AS', alpha_3: 'LAO'},
    { code: 'LV', name: 'Latvia', phone: 371, symbol: '€', capital: 'Riga', currency: 'EUR', continent_code: 'EU', alpha_3: 'LVA'},
    { code: 'LB', name: 'Lebanon', phone: 961, symbol: '£', capital: 'Beirut', currency: 'LBP', continent_code: 'AS', alpha_3: 'LBN'},
    { code: 'LS', name: 'Lesotho', phone: 266, symbol: 'L', capital: 'Maseru', currency: 'LSL', continent_code: 'AF', alpha_3: 'LSO'},
    { code: 'LR', name: 'Liberia', phone: 231, symbol: '$', capital: 'Monrovia', currency: 'LRD', continent_code: 'AF', alpha_3: 'LBR'},
    { code: 'LY', name: 'Libyan Arab Jamahiriya', phone: 218, symbol: 'د.ل', capital: 'Tripolis', currency: 'LYD', continent_code: 'AF', alpha_3: 'LBY'},
    { code: 'LI', name: 'Liechtenstein', phone: 423, symbol: 'CHf', capital: 'Vaduz', currency: 'CHF', continent_code: 'EU', alpha_3: 'LIE'},
    { code: 'LT', name: 'Lithuania', phone: 370, symbol: '€', capital: 'Vilnius', currency: 'EUR', continent_code: 'EU', alpha_3: 'LTU'},
    { code: 'LU', name: 'Luxembourg', phone: 352, symbol: '€', capital: 'Luxembourg', currency: 'EUR', continent_code: 'EU', alpha_3: 'LUX'},
    { code: 'MO', name: 'Macao', phone: 853, symbol: '$', capital: 'Macao', currency: 'MOP', continent_code: 'AS', alpha_3: 'MAC'},
    { code: 'MK', name: 'Macedonia, the Former Yugoslav Republic of', phone: 389, symbol: 'ден', capital: 'Skopje', currency: 'MKD', continent_code: 'EU', alpha_3: 'MKD'},
    { code: 'MG', name: 'Madagascar', phone: 261, symbol: 'Ar', capital: 'Antananarivo', currency: 'MGA', continent_code: 'AF', alpha_3: 'MDG'},
    { code: 'MW', name: 'Malawi', phone: 265, symbol: 'MK', capital: 'Lilongwe', currency: 'MWK', continent_code: 'AF', alpha_3: 'MWI'},
    { code: 'MY', name: 'Malaysia', phone: 60, symbol: 'RM', capital: 'Kuala Lumpur', currency: 'MYR', continent_code: 'AS', alpha_3: 'MYS'},
    { code: 'MV', name: 'Maldives', phone: 960, symbol: 'Rf', capital: 'Male', currency: 'MVR', continent_code: 'AS', alpha_3: 'MDV'},
    { code: 'ML', name: 'Mali', phone: 223, symbol: 'CFA', capital: 'Bamako', currency: 'XOF', continent_code: 'AF', alpha_3: 'MLI'},
    { code: 'MT', name: 'Malta', phone: 356, symbol: '€', capital: 'Valletta', currency: 'EUR', continent_code: 'EU', alpha_3: 'MLT'},
    { code: 'MH', name: 'Marshall Islands', phone: 692, symbol: '$', capital: 'Majuro', currency: 'USD', continent_code: 'OC', alpha_3: 'MHL'},
    { code: 'MQ', name: 'Martinique', phone: 596, symbol: '€', capital: 'Fort-de-France', currency: 'EUR', continent_code: 'NA', alpha_3: 'MTQ'},
    { code: 'MR', name: 'Mauritania', phone: 222, symbol: 'MRU', capital: 'Nouakchott', currency: 'MRO', continent_code: 'AF', alpha_3: 'MRT'},
    { code: 'MU', name: 'Mauritius', phone: 230, symbol: '₨', capital: 'Port Louis', currency: 'MUR', continent_code: 'AF', alpha_3: 'MUS'},
    { code: 'YT', name: 'Mayotte', phone: 262, symbol: '€', capital: 'Mamoudzou', currency: 'EUR', continent_code: 'AF', alpha_3: 'MYT'},
    { code: 'MX', name: 'Mexico', phone: 52, symbol: '$', capital: 'Mexico City', currency: 'MXN', continent_code: 'NA', alpha_3: 'MEX'},
    { code: 'FM', name: 'Micronesia, Federated States of', phone: 691, symbol: '$', capital: 'Palikir', currency: 'USD', continent_code: 'OC', alpha_3: 'FSM'},
    { code: 'MD', name: 'Moldova, Republic of', phone: 373, symbol: 'L', capital: 'Chisinau', currency: 'MDL', continent_code: 'EU', alpha_3: 'MDA'},
    { code: 'MC', name: 'Monaco', phone: 377, symbol: '€', capital: 'Monaco', currency: 'EUR', continent_code: 'EU', alpha_3: 'MCO'},
    { code: 'MN', name: 'Mongolia', phone: 976, symbol: '₮', capital: 'Ulan Bator', currency: 'MNT', continent_code: 'AS', alpha_3: 'MNG'},
    { code: 'ME', name: 'Montenegro', phone: 382, symbol: '€', capital: 'Podgorica', currency: 'EUR', continent_code: 'EU', alpha_3: 'MNE'},
    { code: 'MS', name: 'Montserrat', phone: 1664, symbol: '$', capital: 'Plymouth', currency: 'XCD', continent_code: 'NA', alpha_3: 'MSR'},
    { code: 'MA', name: 'Morocco', phone: 212, symbol: 'DH', capital: 'Rabat', currency: 'MAD', continent_code: 'AF', alpha_3: 'MAR'},
    { code: 'MZ', name: 'Mozambique', phone: 258, symbol: 'MT', capital: 'Maputo', currency: 'MZN', continent_code: 'AF', alpha_3: 'MOZ'},
    { code: 'MM', name: 'Myanmar', phone: 95, symbol: 'K', capital: 'Nay Pyi Taw', currency: 'MMK', continent_code: 'AS', alpha_3: 'MMR'},
    { code: 'NA', name: 'Namibia', phone: 264, symbol: '$', capital: 'Windhoek', currency: 'NAD', continent_code: 'AF', alpha_3: 'NAM'},
    { code: 'NR', name: 'Nauru', phone: 674, symbol: '$', capital: 'Yaren', currency: 'AUD', continent_code: 'OC', alpha_3: 'NRU'},
    { code: 'NP', name: 'Nepal', phone: 977, symbol: '₨', capital: 'Kathmandu', currency: 'NPR', continent_code: 'AS', alpha_3: 'NPL'},
    { code: 'NL', name: 'Netherlands', phone: 31, symbol: '€', capital: 'Amsterdam', currency: 'EUR', continent_code: 'EU', alpha_3: 'NLD'},
    { code: 'AN', name: 'Netherlands Antilles', phone: 599, symbol: 'NAf', capital: 'Willemstad', currency: 'ANG', continent_code: 'NA', alpha_3: 'ANT'},
    { code: 'NC', name: 'New Caledonia', phone: 687, symbol: '₣', capital: 'Noumea', currency: 'XPF', continent_code: 'OC', alpha_3: 'NCL'},
    { code: 'NZ', name: 'New Zealand', phone: 64, symbol: '$', capital: 'Wellington', currency: 'NZD', continent_code: 'OC', alpha_3: 'NZL'},
    { code: 'NI', name: 'Nicaragua', phone: 505, symbol: 'C$', capital: 'Managua', currency: 'NIO', continent_code: 'NA', alpha_3: 'NIC'},
    { code: 'NE', name: 'Niger', phone: 227, symbol: 'CFA', capital: 'Niamey', currency: 'XOF', continent_code: 'AF', alpha_3: 'NER'},
    { code: 'NG', name: 'Nigeria', phone: 234, symbol: '₦', capital: 'Abuja', currency: 'NGN', continent_code: 'AF', alpha_3: 'NGA'},
    { code: 'NU', name: 'Niue', phone: 683, symbol: '$', capital: 'Alofi', currency: 'NZD', continent_code: 'OC', alpha_3: 'NIU'},
    { code: 'NF', name: 'Norfolk Island', phone: 672, symbol: '$', capital: 'Kingston', currency: 'AUD', continent_code: 'OC', alpha_3: 'NFK'},
    { code: 'MP', name: 'Northern Mariana Islands', phone: 1670, symbol: '$', capital: 'Saipan', currency: 'USD', continent_code: 'OC', alpha_3: 'MNP'},
    { code: 'NO', name: 'Norway', phone: 47, symbol: 'kr', capital: 'Oslo', currency: 'NOK', continent_code: 'EU', alpha_3: 'NOR'},
    { code: 'OM', name: 'Oman', phone: 968, symbol: '.ع.ر', capital: 'Muscat', currency: 'OMR', continent_code: 'AS', alpha_3: 'OMN'},
    { code: 'PK', name: 'Pakistan', phone: 92, symbol: '₨', capital: 'Islamabad', currency: 'PKR', continent_code: 'AS', alpha_3: 'PAK'},
    { code: 'PW', name: 'Palau', phone: 680, symbol: '$', capital: 'Melekeok', currency: 'USD', continent_code: 'OC', alpha_3: 'PLW'},
    { code: 'PS', name: 'Palestinian Territory, Occupied', phone: 970, symbol: '₪', capital: 'East Jerusalem', currency: 'ILS', continent_code: 'AS', alpha_3: 'PSE'},
    { code: 'PA', name: 'Panama', phone: 507, symbol: 'B/.', capital: 'Panama City', currency: 'PAB', continent_code: 'NA', alpha_3: 'PAN'},
    { code: 'PG', name: 'Papua New Guinea', phone: 675, symbol: 'K', capital: 'Port Moresby', currency: 'PGK', continent_code: 'OC', alpha_3: 'PNG'},
    { code: 'PY', name: 'Paraguay', phone: 595, symbol: '₲', capital: 'Asuncion', currency: 'PYG', continent_code: 'SA', alpha_3: 'PRY'},
    { code: 'PE', name: 'Peru', phone: 51, symbol: 'S/.', capital: 'Lima', currency: 'PEN', continent_code: 'SA', alpha_3: 'PER'},
    { code: 'PH', name: 'Philippines', phone: 63, symbol: '₱', capital: 'Manila', currency: 'PHP', continent_code: 'AS', alpha_3: 'PHL'},
    { code: 'PN', name: 'Pitcairn', phone: 64, symbol: '$', capital: 'Adamstown', currency: 'NZD', continent_code: 'OC', alpha_3: 'PCN'},
    { code: 'PL', name: 'Poland', phone: 48, symbol: 'zł', capital: 'Warsaw', currency: 'PLN', continent_code: 'EU', alpha_3: 'POL'},
    { code: 'PT', name: 'Portugal', phone: 351, symbol: '€', capital: 'Lisbon', currency: 'EUR', continent_code: 'EU', alpha_3: 'PRT'},
    { code: 'PR', name: 'Puerto Rico', phone: 1787, symbol: '$', capital: 'San Juan', currency: 'USD', continent_code: 'NA', alpha_3: 'PRI'},
    { code: 'QA', name: 'Qatar', phone: 974, symbol: 'ق.ر', capital: 'Doha', currency: 'QAR', continent_code: 'AS', alpha_3: 'QAT'},
    { code: 'RE', name: 'Reunion', phone: 262, symbol: '€', capital: 'Saint-Denis', currency: 'EUR', continent_code: 'AF', alpha_3: 'REU'},
    { code: 'RO', name: 'Romania', phone: 40, symbol: 'lei', capital: 'Bucharest', currency: 'RON', continent_code: 'EU', alpha_3: 'ROM'},
    { code: 'RU', name: 'Russian Federation', phone: 7, symbol: '₽', capital: 'Moscow', currency: 'RUB', continent_code: 'AS', alpha_3: 'RUS'},
    { code: 'RW', name: 'Rwanda', phone: 250, symbol: 'FRw', capital: 'Kigali', currency: 'RWF', continent_code: 'AF', alpha_3: 'RWA'},
    { code: 'BL', name: 'Saint Barthelemy', phone: 590, symbol: '€', capital: 'Gustavia', currency: 'EUR', continent_code: 'NA', alpha_3: 'BLM'},
    { code: 'SH', name: 'Saint Helena', phone: 290, symbol: '£', capital: 'Jamestown', currency: 'SHP', continent_code: 'AF', alpha_3: 'SHN'},
    { code: 'KN', name: 'Saint Kitts and Nevis', phone: 1869, symbol: '$', capital: 'Basseterre', currency: 'XCD', continent_code: 'NA', alpha_3: 'KNA'},
    { code: 'LC', name: 'Saint Lucia', phone: 1758, symbol: '$', capital: 'Castries', currency: 'XCD', continent_code: 'NA', alpha_3: 'LCA'},
    { code: 'MF', name: 'Saint Martin', phone: 590, symbol: '€', capital: 'Marigot', currency: 'EUR', continent_code: 'NA', alpha_3: 'MAF'},
    { code: 'PM', name: 'Saint Pierre and Miquelon', phone: 508, symbol: '€', capital: 'Saint-Pierre', currency: 'EUR', continent_code: 'NA', alpha_3: 'SPM'},
    { code: 'VC', name: 'Saint Vincent and the Grenadines', phone: 1784, symbol: '$', capital: 'Kingstown', currency: 'XCD', continent_code: 'NA', alpha_3: 'VCT'},
    { code: 'WS', name: 'Samoa', phone: 684, symbol: 'SAT', capital: 'Apia', currency: 'WST', continent_code: 'OC', alpha_3: 'WSM'},
    { code: 'SM', name: 'San Marino', phone: 378, symbol: '€', capital: 'San Marino', currency: 'EUR', continent_code: 'EU', alpha_3: 'SMR'},
    { code: 'ST', name: 'Sao Tome and Principe', phone: 239, symbol: 'Db', capital: 'Sao Tome', currency: 'STD', continent_code: 'AF', alpha_3: 'STP'},
    { code: 'SA', name: 'Saudi Arabia', phone: 966, symbol: '﷼', capital: 'Riyadh', currency: 'SAR', continent_code: 'AS', alpha_3: 'SAU'},
    { code: 'SN', name: 'Senegal', phone: 221, symbol: 'CFA', capital: 'Dakar', currency: 'XOF', continent_code: 'AF', alpha_3: 'SEN'},
    { code: 'RS', name: 'Serbia', phone: 381, symbol: 'din', capital: 'Belgrade', currency: 'RSD', continent_code: 'EU', alpha_3: 'SRB'},
    { code: 'CS', name: 'Serbia and Montenegro', phone: 381, symbol: 'din', capital: 'Belgrade', currency: 'RSD', continent_code: 'EU', alpha_3: 'SCG'},
    { code: 'SC', name: 'Seychelles', phone: 248, symbol: 'SRe', capital: 'Victoria', currency: 'SCR', continent_code: 'AF', alpha_3: 'SYC'},
    { code: 'SL', name: 'Sierra Leone', phone: 232, symbol: 'Le', capital: 'Freetown', currency: 'SLL', continent_code: 'AF', alpha_3: 'SLE'},
    { code: 'SG', name: 'Singapore', phone: 65, symbol: '$', capital: 'Singapur', currency: 'SGD', continent_code: 'AS', alpha_3: 'SGP'},
    { code: 'SX', name: 'Sint Maarten', phone: 721, symbol: 'ƒ', capital: 'Philipsburg', currency: 'ANG', continent_code: 'NA', alpha_3: 'SXM'},
    { code: 'SK', name: 'Slovakia', phone: 421, symbol: '€', capital: 'Bratislava', currency: 'EUR', continent_code: 'EU', alpha_3: 'SVK'},
    { code: 'SI', name: 'Slovenia', phone: 386, symbol: '€', capital: 'Ljubljana', currency: 'EUR', continent_code: 'EU', alpha_3: 'SVN'},
    { code: 'SB', name: 'Solomon Islands', phone: 677, symbol: 'Si$', capital: 'Honiara', currency: 'SBD', continent_code: 'OC', alpha_3: 'SLB'},
    { code: 'SO', name: 'Somalia', phone: 252, symbol: 'Sh.so.', capital: 'Mogadishu', currency: 'SOS', continent_code: 'AF', alpha_3: 'SOM'},
    { code: 'ZA', name: 'South Africa', phone: 27, symbol: 'R', capital: 'Pretoria', currency: 'ZAR', continent_code: 'AF', alpha_3: 'ZAF'},
    { code: 'GS', name: 'South Georgia and the South Sandwich Islands', phone: 500, symbol: '£', capital: 'Grytviken', currency: 'GBP', continent_code: 'AN', alpha_3: 'SGS'},
    { code: 'SS', name: 'South Sudan', phone: 211, symbol: '£', capital: 'Juba', currency: 'SSP', continent_code: 'AF', alpha_3: 'SSD'},
    { code: 'ES', name: 'Spain', phone: 34, symbol: '€', capital: 'Madrid', currency: 'EUR', continent_code: 'EU', alpha_3: 'ESP'},
    { code: 'LK', name: 'Sri Lanka', phone: 94, symbol: 'Rs', capital: 'Colombo', currency: 'LKR', continent_code: 'AS', alpha_3: 'LKA'},
    { code: 'SD', name: 'Sudan', phone: 249, symbol: '.س.ج', capital: 'Khartoum', currency: 'SDG', continent_code: 'AF', alpha_3: 'SDN'},
    { code: 'SR', name: 'Suriname', phone: 597, symbol: '$', capital: 'Paramaribo', currency: 'SRD', continent_code: 'SA', alpha_3: 'SUR'},
    { code: 'SJ', name: 'Svalbard and Jan Mayen', phone: 47, symbol: 'kr', capital: 'Longyearbyen', currency: 'NOK', continent_code: 'EU', alpha_3: 'SJM'},
    { code: 'SZ', name: 'Swaziland', phone: 268, symbol: 'E', capital: 'Mbabane', currency: 'SZL', continent_code: 'AF', alpha_3: 'SWZ'},
    { code: 'SE', name: 'Sweden', phone: 46, symbol: 'kr', capital: 'Stockholm', currency: 'SEK', continent_code: 'EU', alpha_3: 'SWE'},
    { code: 'CH', name: 'Switzerland', phone: 41, symbol: 'CHf', capital: 'Berne', currency: 'CHF', continent_code: 'EU', alpha_3: 'CHE'},
    { code: 'SY', name: 'Syrian Arab Republic', phone: 963, symbol: 'LS', capital: 'Damascus', currency: 'SYP', continent_code: 'AS', alpha_3: 'SYR'},
    { code: 'TW', name: 'Taiwan, Province of China', phone: 886, symbol: '$', capital: 'Taipei', currency: 'TWD', continent_code: 'AS', alpha_3: 'TWN'},
    { code: 'TJ', name: 'Tajikistan', phone: 992, symbol: 'SM', capital: 'Dushanbe', currency: 'TJS', continent_code: 'AS', alpha_3: 'TJK'},
    { code: 'TZ', name: 'Tanzania, United Republic of', phone: 255, symbol: 'TSh', capital: 'Dodoma', currency: 'TZS', continent_code: 'AF', alpha_3: 'TZA'},
    { code: 'TH', name: 'Thailand', phone: 66, symbol: '฿', capital: 'Bangkok', currency: 'THB', continent_code: 'AS', alpha_3: 'THA'},
    { code: 'TL', name: 'Timor-Leste', phone: 670, symbol: '$', capital: 'Dili', currency: 'USD', continent_code: 'AS', alpha_3: 'TLS'},
    { code: 'TG', name: 'Togo', phone: 228, symbol: 'CFA', capital: 'Lome', currency: 'XOF', continent_code: 'AF', alpha_3: 'TGO'},
    { code: 'TK', name: 'Tokelau', phone: 690, symbol: '$', capital: '', currency: 'NZD', continent_code: 'OC', alpha_3: 'TKL'},
    { code: 'TO', name: 'Tonga', phone: 676, symbol: '$', capital: 'Nukualofa', currency: 'TOP', continent_code: 'OC', alpha_3: 'TON'},
    { code: 'TT', name: 'Trinidad and Tobago', phone: 1868, symbol: '$', capital: 'Port of Spain', currency: 'TTD', continent_code: 'NA', alpha_3: 'TTO'},
    { code: 'TN', name: 'Tunisia', phone: 216, symbol: 'ت.د', capital: 'Tunis', currency: 'TND', continent_code: 'AF', alpha_3: 'TUN'},
    { code: 'TR', name: 'Turkey', phone: 90, symbol: '₺', capital: 'Ankara', currency: 'TRY', continent_code: 'AS', alpha_3: 'TUR'},
    { code: 'TM', name: 'Turkmenistan', phone: 7370, symbol: 'T', capital: 'Ashgabat', currency: 'TMT', continent_code: 'AS', alpha_3: 'TKM'},
    { code: 'TC', name: 'Turks and Caicos Islands', phone: 1649, symbol: '$', capital: 'Cockburn Town', currency: 'USD', continent_code: 'NA', alpha_3: 'TCA'},
    { code: 'TV', name: 'Tuvalu', phone: 688, symbol: '$', capital: 'Funafuti', currency: 'AUD', continent_code: 'OC', alpha_3: 'TUV'},
    { code: 'UG', name: 'Uganda', phone: 256, symbol: 'USh', capital: 'Kampala', currency: 'UGX', continent_code: 'AF', alpha_3: 'UGA'},
    { code: 'UA', name: 'Ukraine', phone: 380, symbol: '₴', capital: 'Kiev', currency: 'UAH', continent_code: 'EU', alpha_3: 'UKR'},
    { code: 'AE', name: 'United Arab Emirates', phone: 971, symbol: 'إ.د', capital: 'Abu Dhabi', currency: 'AED', continent_code: 'AS', alpha_3: 'ARE'},
    { code: 'GB', name: 'United Kingdom', phone: 44, symbol: '£', capital: 'London', currency: 'GBP', continent_code: 'EU', alpha_3: 'GBR'},
    { code: 'US', name: 'United States', phone: 1, symbol: '$', capital: 'Washington', currency: 'USD', continent_code: 'NA', alpha_3: 'USA'},
    { code: 'UM', name: 'United States Minor Outlying Islands', phone: 1, symbol: '$', capital: '', currency: 'USD', continent_code: 'NA', alpha_3: 'UMI'},
    { code: 'UY', name: 'Uruguay', phone: 598, symbol: '$', capital: 'Montevideo', currency: 'UYU', continent_code: 'SA', alpha_3: 'URY'},
    { code: 'UZ', name: 'Uzbekistan', phone: 998, symbol: 'лв', capital: 'Tashkent', currency: 'UZS', continent_code: 'AS', alpha_3: 'UZB'},
    { code: 'VU', name: 'Vanuatu', phone: 678, symbol: 'VT', capital: 'Port Vila', currency: 'VUV', continent_code: 'OC', alpha_3: 'VUT'},
    { code: 'VE', name: 'Venezuela', phone: 58, symbol: 'Bs', capital: 'Caracas', currency: 'VEF', continent_code: 'SA', alpha_3: 'VEN'},
    { code: 'VN', name: 'Viet Nam', phone: 84, symbol: '₫', capital: 'Hanoi', currency: 'VND', continent_code: 'AS', alpha_3: 'VNM'},
    { code: 'VG', name: 'Virgin Islands, British', phone: 1284, symbol: '$', capital: 'Road Town', currency: 'USD', continent_code: 'NA', alpha_3: 'VGB'},
    { code: 'VI', name: 'Virgin Islands, U.s.', phone: 1340, symbol: '$', capital: 'Charlotte Amalie', currency: 'USD', continent_code: 'NA', alpha_3: 'VIR'},
    { code: 'WF', name: 'Wallis and Futuna', phone: 681, symbol: '₣', capital: 'Mata Utu', currency: 'XPF', continent_code: 'OC', alpha_3: 'WLF'},
    { code: 'EH', name: 'Western Sahara', phone: 212, symbol: 'MAD', capital: 'El-Aaiun', currency: 'MAD', continent_code: 'AF', alpha_3: 'ESH'},
    { code: 'YE', name: 'Yemen', phone: 967, symbol: '﷼', capital: 'Sanaa', currency: 'YER', continent_code: 'AS', alpha_3: 'YEM'},
    { code: 'ZM', name: 'Zambia', phone: 260, symbol: 'ZK', capital: 'Lusaka', currency: 'ZMW', continent_code: 'AF', alpha_3: 'ZMB'},
    { code: 'ZW', name: 'Zimbabwe', phone: 263, symbol: '$', capital: 'Harare', currency: 'ZWL', continent_code: 'AF', alpha_3: 'ZWE'},
  ]);

  await knex('persons').del();
  await knex('persons').insert([
    { last_name: 'Doe', first_name: 'John', country_code: 'US' },
    { last_name: 'Cole', first_name: 'Adam', country_code: 'EU' },
    { last_name: 'Best', first_name: 'Gianluca', country_code: 'GB' },
    { last_name: 'Lyons', first_name: 'Brianna', country_code: 'AU' },
    { last_name: 'Mcmillan', first_name: 'Zoe', country_code: 'US' },
    { last_name: 'Baker', first_name: 'Liam', country_code: 'AU' },
    { last_name: 'Armstrong', first_name: 'Sophie', country_code: 'NL' },
    { last_name: 'Mercado', first_name: 'Alannah', country_code: 'MX' },
    { last_name: 'Lee', first_name: 'John', country_code: 'HK' },
    { last_name: 'Xi', first_name: 'JP', country_code: 'CN' },
    { last_name: 'Ruairi', first_name: 'Blake', country_code: 'IN' },
    { last_name: 'Richards', first_name: 'Hayley', country_code: 'ZA' },
    { last_name: 'Harris', first_name: 'Ella', country_code: 'ZA' },
  ])
};
